name: polly_dart
description: A Dart port of Polly (.NET resilience library) providing strategies like Retry, Circuit Breaker, Timeout, Rate Limiter, Hedging, and Fallback.
version: 0.0.2
homepage: https://www.anirudhsingh.in
repository: https://github.com/flutterninja9/polly_dart

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
